image: debian:stable-20200414

stages:
  - build

build_and_install:
  stage: build
  tags:
    - local
  before_script:
    - apt update && apt install -y build-essential bison flex python pkg-config autoconf automake git gettext autopoint libfuse-dev libdevmapper-dev libfreetype6-dev
  script:
    - ./bootstrap
    - ./configure
    - make -j2
    - make install
    - grub-install --version
    - ls /usr/local/lib/grub/i386-pc/slaunch.module
    - ls /usr/local/lib/grub/i386-pc/slaunch.mod
