stages:
  - build

build_and_install:
  image: debian:stable-20200414
  stage: build
  except:
    - debian
  tags:
    - local
  before_script:
    - apt update && apt install -y build-essential bison flex python pkg-config autoconf automake git gettext autopoint libfuse-dev libdevmapper-dev libfreetype6-dev
  script:
    - ./bootstrap
    - ./configure
    - make -j2
    - make install
    - grub-install --version
    - ls /usr/local/lib/grub/i386-pc/slaunch.module
    - ls /usr/local/lib/grub/i386-pc/slaunch.mod

build_nixpkg:
  stage: build
  except:
    - debian
  variables:
    NIXPKG: "grub"
    GRUB_COMMIT: "$CI_COMMIT_SHA"
    GRUB_TAG: "$CI_COMMIT_REF_NAME"
  trigger:
    project: trenchboot1/3mdeb/nixos-trenchboot-configs
    branch: master
    strategy: depend

build_debian_pkg:
  image: debian:bullseye-20200514
  stage: build
  only:
    - debian
  before_script:
    - ./.gitlab-ci/install-debian-build-deps.sh
    - ln -s /usr/bin/python3 /usr/bin/python
    - ./bootstrap.sh
  script:
    - dpkg-buildpackage -b -rfakeroot --target-arch i386 -us -uc
    - mkdir artifacts && mv ../*.deb artifacts/
    - dpkg -c artifacts/*.deb
  artifacts:
    paths:
      - artifacts/*
